name: preview
on: pull_request
jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create preview - order-eat
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto
          working-directory: apps/order-eat

      - name: Create preview - order-eat-tablet
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto
          working-directory: apps/order-eat-tablet